name: Deployment

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Check Node Version
        run: node -v

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build
